---
- name: consul-template assemble
  assemble:
    src: "{{ consul_template_home }}/config/fragments"
    dest: "{{ consul_template_home }}/config/{{ consul_template_config_file }}"
    regexp: '.*cfg$'
    mode: 0755
  notify: supervisord restart consul-template

- name: supervisord restart consul-template
  supervisorctl: name=consul-template state=restarted
  when: consul_template_supervisor_enabled
  ignore_errors: true
